matrix:
  include:
    language: java
    
    language: android
    
android:
   components:
      - tools
      - platform-tools
      - tools
     
  # The BuildTools version used by your project
      - build-tools-28.0.3

  # The SDK version used to compile your project
      - android-27
      

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
      - sys-img-armeabi-v7a-android-28
      - sys-img-armeabi-v7a-android-17

after_success:
- bash <(curl -s https://codecov.io/bash)
