matrix:
  include:
    language: java
    
    language: android

    
android:
   components:
      - tools
      - platform-tools
      - tools
     
  # The BuildTools version used by your project
      - build-tools-28.0.3

  # The SDK version used to compile your project
      - android-27

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  CODECOV_TOKEN="6e1b91c8-0b05-4f97-b895-c81981813c43"

script:
  - ./gradlew build check

